# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: fortio/fortio.build:v3
    working_directory: /go/src/istio.io/fortio
    steps:
      - setup_remote_docker:
          version: 17.10.0-ce
      - checkout
      - run: make test
      - run: CGO_ENABLED=0 make install local-lint
      - run: make webtest
      - run: make coverage
